### ISSUE TITLE
frontend

### ISSUE THREAD

**Issue by Guellaf** [NiclasvanEyk/initializer-for-laravel#59]
![image](https://user-images.githubusercontent.com/47402966/139912701-45d637a8-1eac-4590-a2dd-e6a73dfd6bfd.png)

![image](https://user-images.githubusercontent.com/47402966/139764888-387119e3-ba5e-46b1-9e4b-d594d5502844.png)

**Comment by NiclasvanEyk** [comment]
Hi @Guellaf, thanks for filing an issue!

Could you maybe share more details on the steps you took to arrive at this error? When I select Jetstream with the Inertia option and make no other adjustments to the defaults, everything just works fine. Did any errors occur while running `./initialize`?

**Comment by Guellaf** [comment]
step 1) 
![image](https://user-images.githubusercontent.com/47402966/139912882-a8ed8266-9254-4348-bd97-48b92da1cf17.png)
step 2)
![image](https://user-images.githubusercontent.com/47402966/139912918-705d7a3b-7680-40dc-94d9-263c74b5f9ef.png)
step 3) 
![image](https://user-images.githubusercontent.com/47402966/139912963-65f70b98-41ac-49ac-ac63-615a4c1bd112.png)
step 4)
![image](https://user-images.githubusercontent.com/47402966/139913023-09457d4c-bb42-4c8e-8e1c-ac2744a1e0f9.png)
step 5)
![image](https://user-images.githubusercontent.com/47402966/139913052-58d36c62-7a58-4194-a634-29fd310cbb4b.png)
step 6)
![image](https://user-images.githubusercontent.com/47402966/139913113-b21219c1-d14a-4c25-9ca3-30a69bc364fe.png)
step 7)
![image](https://user-images.githubusercontent.com/47402966/139913167-1dde556d-94ca-4ab7-843a-3fcff473972d.png)
step 8)
![image](https://user-images.githubusercontent.com/47402966/139913221-4137835d-7d78-4fe3-beef-949ae8338fe7.png)
step 9)
![image](https://user-images.githubusercontent.com/47402966/139913332-9e230cc1-953c-4f0d-95db-acb1e2bf434c.png)
step 10)
![image](https://user-images.githubusercontent.com/47402966/139913390-6b46a649-fe84-4a48-82f3-b61a3006c789.png)
result)
[[shop.zip](https://github.com/NiclasvanEyk/initializer-for-laravel/files/7462736/shop.zip)](url)
other steps off laravel composer install & cp .env ... & config .env & migrate & serv

**Comment by Guellaf** [comment]
I selected livewire but code source with inertia

**Comment by NiclasvanEyk** [comment]
It looks like you did not run the `initialize` script included with the application, am I right?
There is no need to run composer install, etc. this is all done by the `initialize` script that should be run after unzipping, as described in the image in step 10.

**Comment by NiclasvanEyk** [comment]
As part of the installation process, the script then runs `php artisan jetstream:install inertia`, which actually installs inertia and the other selected components.
