### ISSUE TITLE
Composer error during ./initialize

### ISSUE THREAD

**Issue by fladderen** [NiclasvanEyk/initializer-for-laravel#71]
After downloading the zipfile and running ./initialize the following error occurred; 

`Running initial installation inside 'laravelsail/php80-composer:latest'
No lock file found. Updating dependencies instead of installing from lock file. Use composer update over composer install if you do not have a lock file.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires laravel/horizon ^0.1.0 -> satisfiable by laravel/horizon[v0.1.0].
    - Conclusion: don't install laravel/framework v8.70.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.70.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.70.0 (conflict analysis result)
    - laravel/horizon v0.1.0 requires illuminate/support ~5.4 -> satisfiable by illuminate/support[v5.4.0, ..., 5.8.x-dev].
    - Only one of these can be installed: illuminate/support[dev-master, v5.4.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev], laravel/framework[v8.70.0, v8.70.1, v8.70.2, 8.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
    - Root composer.json requires laravel/framework ^8.70 -> satisfiable by laravel/framework[v8.70.0, v8.70.1, v8.70.2, 8.x-dev].`

In the composer file the following package versions are set;

`"require": {
        ....
        "laravel/framework": "^8.65",
        ...
    },
    "require-dev": {
        ...
        "laravel/horizon": "^0.1.0",
        ...
    },`

The chose packages and configurations can be found through this link; https://laravel.initializer.dev/?preset&vendor=fladderen&php=8.0&starter=breeze&database=mysql&cache=redis&queue=redis&uses-horizon&uses-telescope&uses-mailhog

For now I was able to fix this by manually updating Laravel and Horizon to their latest versions. It seems that especially Horizon wasn't set properly; 

`"require": {
        ...
        "laravel/framework": "^8.70",
        ...
    },
    "require-dev": {
        ...
        "laravel/horizon": "^5.7.15",
        ...
    },`

**Comment by NiclasvanEyk** [comment]
Wow, that's a really really old version of horizon. I wonder why this was chosen instead of a more recent one.

Hopefully I'll find some time over the weekend and will look further into this.

**Comment by NiclasvanEyk** [comment]
Fixing #69 seems to have also fixed this issue. I'd guess the Horizon 0.1.0 was the only version that did not use a platform package. It now seems to use `ext-pcntl` and `ext-posix`, which is why the old version was selected.

Now that platform package constraints are ignored while resolving versions (the images for sail include almost every PHP extension anyway), the proper, more up-to-date versions are selected. At least when I now generate a project using the link you have kindly provided, the zip contains `^5.7`. If something still does not seem to work correctly, just comment and I'll reopen the issue again.
